# gitversion will change the version number
version: x-{build}

environment:
  COVERALLS_REPO_TOKEN:
    secure: JSfpTkHnbxXX3F54lOrfSkCbwzdQED+Ki/mjL7+2NNPfMgIFC/a4RHDgOtNX+1pW
  chocoKey:
    secure: Auc6eQGP6pNj7NMbHMQHNn7F3rTzqwQBDB1PoxDnoyxT819GKaU/Nbe3xEJYmHED

# tools we need for bulding/testing/deploying
install:
  - choco install gitversion.portable -pre -y
  - nuget install secure-file -ExcludeVersion
  - if defined snk_secret secure-file\tools\secure-file -decrypt src\ipfs.ci.snk.enc -secret %snk_secret% -out src\ipfs.dev.snk
  - choco install ipfs
  - ipfs init
  - ps: Start-Process -FilePath "ipfs.exe" -ArgumentList "daemon"
  # need windows update server running for dokany
  - ps: Set-Service wuauserv -StartupType Manual
  - ps: Start-Service wuauserv
  - cmd: choco install dokany

pull_requests:
  do_not_increment_build_number: true

# gitversion will change the assembly info
assembly_info:
  patch: false

before_build:
  - nuget restore
  - ps: gitversion /output buildserver /updateAssemblyInfo >gitversion.log

platform: Any CPU
configuration: Release

build:
  project: IpfsMount.sln
  publish_nuget: false
  verbosity: minimal

after_build:
  - echo %GitVersion_NuGetVersion%
  - cmd: choco pack IpfsMount.nuspec -version "%GitVersion_NuGetVersion%" 
  - cmd: appveyor PushArtifact "ipfs-mount.%GitVersion_NuGetVersion%.nupkg"

after_test: 
# Generate coverage report
    - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[ipfs-mount]*" -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:./IpfsMountTests/bin/Release/Ipfs.VirtualDisk.Tests.dll" -output:coverage.xml
    - if defined COVERALLS_REPO_TOKEN packages\coveralls.net.0.7.0\tools\csmacnz.coveralls.exe --opencover -i ./coverage.xml --serviceName appveyor --jobId %APPVEYOR_BUILD_NUMBER%

deploy_script:
  - ps: >-
      if($env:APPVEYOR_REPO_BRANCH -eq 'master' -And $env:APPVEYOR_REPO_TAG -eq 'true') {
        $version = $env:GitVersion_NuGetVersion ;
        choco apiKey -k $env:chocoKey -source https://chocolatey.org/ ;
        choco push ipfs-mount.$version.nupkg
      }
